<!DOCTYPE html>
<html>
<head>
    <title>Payment Proof #{{ $bill->id }}</title>
    <style>
        body { font-family: sans-serif; padding: 30px; color: #333; }
        .header { text-align: center; margin-bottom: 40px; border-bottom: 2px solid #eee; padding-bottom: 20px; }
        .header h1 { margin: 0; font-size: 24px; text-transform: uppercase; letter-spacing: 1px; }
        .header p { margin: 5px 0 0; color: #666; font-size: 12px; }
        
        .info-grid { width: 100%; margin-bottom: 30px; }
        .info-grid td { padding: 5px; vertical-align: top; }
        .label { font-weight: bold; font-size: 12px; color: #888; text-transform: uppercase; }
        .value { font-size: 14px; font-weight: bold; }

        .proof-section { text-align: center; background: #f9f9f9; padding: 20px; border: 1px solid #eee; border-radius: 5px; }
        .proof-section h3 { margin-top: 0; font-size: 14px; color: #555; }
        img { max-width: 100%; max-height: 500px; border: 1px solid #ddd; margin-top: 10px; }
        
        .footer { position: fixed; bottom: 0; left: 0; right: 0; font-size: 10px; color: #aaa; text-align: center; padding: 10px; border-top: 1px solid #eee; }
        
        .status-badge { 
            display: inline-block; padding: 5px 10px; border-radius: 4px; font-size: 10px; font-weight: bold; text-transform: uppercase; color: white;
            background-color: {{ $bill->status == 'paid' ? '#10B981' : '#F59E0B' }};
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Payment Receipt Verification</h1>
        <p>Generated Invoice Reference #{{ $bill->id }}</p>
    </div>

    <table class="info-grid">
        <tr>
            <td width="50%">
                <div class="label">Tenant Name</div>
                <div class="value">{{ $bill->tenant->name }}</div>
                <div style="font-size: 12px; color: #666;">{{ $bill->tenant->email }}</div>
            </td>
            <td width="50%" style="text-align: right;">
                <div class="label">Property Details</div>
                <div class="value">{{ $bill->tenant->building->name ?? 'N/A' }}</div>
                <div style="font-size: 12px; color: #666;">
                    Floor {{ $bill->tenant->floor_number }}, Unit {{ $bill->tenant->room_number }}
                </div>
            </td>
        </tr>
    </table>

    <table class="info-grid" style="margin-bottom: 40px;">
        <tr>
            <td>
                <div class="label">Billing Month</div>
                <div class="value">{{ $bill->month }}</div>
            </td>
            <td>
                <div class="label">Total Amount</div>
                <div class="value">{{ $bill->currency }} {{ number_format($bill->total) }}</div>
            </td>
            <td>
                <div class="label">Date Paid/Uploaded</div>
                <div class="value">{{ $bill->updated_at->format('d M, Y') }}</div>
            </td>
            <td style="text-align: right;">
                <div class="label">Status</div>
                <div style="margin-top: 4px;"><span class="status-badge">{{ $bill->status }}</span></div>
            </td>
        </tr>
    </table>

    <div class="proof-section">
        <h3>ATTACHED PROOF OF PAYMENT</h3>
        @if($bill->payment_proof)
            <img src="{{ public_path('storage/' . $bill->payment_proof) }}">
        @else
            <p style="color: #999; font-style: italic;">No digital proof image attached.</p>
        @endif
    </div>

    <div class="footer">
        This document is an automated receipt generated by the Building Management System.
    </div>
</body>
</html>