<!DOCTYPE html>
<html>
<head>
    <title>Payment Proof #{{ $bill->id }}</title>
    <style>
        body { font-family: sans-serif; padding: 20px; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #ddd; padding-bottom: 10px; }
        .details { margin-bottom: 20px; font-size: 14px; }
        .proof-box { text-align: center; border: 1px solid #000; padding: 10px; }
        img { max-width: 100%; height: auto; }
        .footer { margin-top: 30px; font-size: 10px; color: #666; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Payment Verification</h1>
        <p>Tenant Payment Receipt Reference</p>
    </div>

    <div class="details">
        <strong>Tenant Name:</strong> {{ $bill->tenant->name }} <br>
        <strong>Building:</strong> {{ $bill->tenant->building->name ?? 'N/A' }} (Unit {{ $bill->tenant->room_number }}) <br>
        <strong>Billing Month:</strong> {{ $bill->month }} <br>
        <strong>Amount Paid:</strong> {{ $bill->currency }} {{ number_format($bill->total) }} <br>
        <strong>Date Uploaded:</strong> {{ $bill->updated_at->format('d M Y') }}
    </div>

    <div class="proof-box">
        <h3>Attached Proof of Payment</h3>
        @if($bill->payment_proof)
            <img src="{{ public_path('storage/' . $bill->payment_proof) }}">
        @else
            <p>No proof image available.</p>
        @endif
    </div>

    <div class="footer">
        Generated by BuildingManager System on {{ date('Y-m-d H:i') }}
    </div>
</body>
</html>